# ====================server====================
server:
  port: 9876
spring:
  thymeleaf:
    # 开发环境禁用页面缓存
    cache: true
    encoding: utf-8
    mode: HTML5
    prefix: classpath:/templates
    suffix: .html
  redis:
    cluster:
        nodes: 10.204.58.11:8080,10.204.58.12:8080,10.204.58.13:8080,10.204.58.14:8080,10.204.58.15:8080,10.204.58.16:8080
    password: K6CJDjjnE9d0OxRjYNKZ
    pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
        min-idle: 4
    timeout: 10000

# ====================doe====================
doe:
  dependency:
    # 用于下载依赖的pom文件
    pom: /app/doe/pom.xml
    # 用于存放下载的jar的目录
    lib: /app/doe/lib/
    # 用于执行mvn命令超时时间（秒）
    timeout: 20
  watchdog:
    url: http://10.204.49.54:8000